spring:
  application:
    name: gateway-service
  
  # OAuth2 Resource Server конфигурация для Keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URL}
          jwk-set-uri: ${JWT_SET_URL}
  

  # Gateway конфигурация
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: video-service
              uri: lb://VIDEO-SERVICE
              predicates:
                - Path=/api/v1/videos/**,/api/v1/users/**
            - id: comment-service
              uri: lb://COMMENT-SERVICE
              predicates:
                - Path=/api/comments/**
            - id: subscription-service
              uri: lb://SUBSCRIPTION-SERVICE
              predicates:
                - Path=/api/v1/subscriptions/**
            - id: notification-service
              uri: lb://NOTIFICATION-SERVICE
              predicates:
                - Path=/api/notifications/**
            - id: recommendation-service
              uri: http://localhost:8000
              predicates:
                - Path=/api/recommendations/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

  instance:
    prefer-ip-address: true

server:
  port: 8081